# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Testing 1
        run: |
          $env:Path = "$env:PGBIN;" + $env:Path
          
          $postgis_url = "https://download.osgeo.org/postgis/windows/pg14/postgis-bundle-pg14-3.3.1x64.zip"
          $postgis_zip = "postgis.zip"
          echo "downloading ..."
          Invoke-WebRequest $postgis_url -OutFile $postgis_zip
          
          Expand-Archive $postgis_zip -DestinationPath $env:PGROOT -Verbose
          Move-Item -Path "$env:PGROOT\postgis-bundle-pg14-3.3.1x64\*" -Destination $env:PGROOT -force

          # echo "--------------------------------- env..."
          # dir env:
          # echo "--------------------------------- $env:PGBIN ..."
          # dir "$env:PGBIN"

          echo "--------------------------------- status..."
          & pg_ctl restart -D "$env:PGDATA"
          & pg_isready
          & psql -c "select version();"
          & psql -c "select extname from pg_extension;"
          & psql -c "CREATE EXTENSION postgis;"


# pushd "$env:PGBIN"
# & "$env:PGBIN\pg_ctl" status
# & "$env:PGBIN\pg_ctl" restart -D "$env:PGDATA"
# popd

#      - uses: actions/checkout@v3
#
#      - name: Testing 2
#        run: |
#          echo "--------------------------------- utils..."
#          pushd windows
#          pg_isready
#          psql
