# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Testing 1
        run: |
          $env:Path = "$env:PGBIN;" + $env:Path
          
          $postgis_url = "https://download.osgeo.org/postgis/windows/pg14/postgis-bundle-pg14x64-setup-3.3.1-1.exe"
          $postgis_msi = "postgis-install.exe"
          Invoke-WebRequest -Uri $postgis_url -OutFile $postgis_msi
          dir $postgis_msi
          
          $postgis_log = "install.log"
          $procMain = Start-Process "msiexec" "/i `"$postgis_msi`" /qn /l*! `"$postgis_log`"" -NoNewWindow -PassThru
          $procLog = Start-Process "powershell" "Get-Content -Path `"$postgis_log`" -Wait" -NoNewWindow -PassThru
          $procMain.WaitForExit()
          $procLog.Kill()
          
          # echo "--------------------------------- env..."
          # dir env:
          # echo "--------------------------------- $env:PGBIN ..."
          # dir "$env:PGBIN"

          echo "--------------------------------- status..."
          & pg_ctl restart -D "$env:PGDATA"
          & pg_isready
          & psql -c "select version();"
          & psql -c "select extname from pg_extension;"


# pushd "$env:PGBIN"
# & "$env:PGBIN\pg_ctl" status
# & "$env:PGBIN\pg_ctl" restart -D "$env:PGDATA"
# popd

#      - uses: actions/checkout@v3
#
#      - name: Testing 2
#        run: |
#          echo "--------------------------------- utils..."
#          pushd windows
#          pg_isready
#          psql
